import path from "path";
import fs from "fs";
import { build } from "vite";

const apps = fs.readdirSync("src/apps");

generateAppIndexFiles(apps);
buildApps(apps);

function buildApps(apps) {
	for (const app of apps) {
		buildApp(app, `${app}.js`, { minify: false });
		buildApp(app, `${app}.min.js`, { minify: true });
	}
}

function buildApp(appName, resultFileName, options) {
	/*
		buildApp("example", { minify: true });
	*/
	build({
		build: {
			lib: {
				entry: path.resolve("src", "apps", appName, "index.ts"),
				name: "globalUdataVariable",
				fileName: () => resultFileName,
				formats: ["umd"],
			},
			target: "es2015",
			minify: options.minify,
		},
	});
}

function generateAppIndexFiles(apps) {
	for (const app of apps) {
		const appConfig = JSON.parse(fs.readFileSync(`src/apps/${app}/build_config.jsonc`));
		const appIndexFileArray = [
			`/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */`,
			`/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */`,
			`/* !!!!!!!!!!!!!!!!!!!!!! THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT THIS FILE. !!!!!!!!!!!!!!!!!!!!!! */`,
			`/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */`,
			`/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */`,
			``,
			`import "../../global/before_app";`,
			`import "./config.ts";`,
			...getImportsForSharedConfig(appConfig.shared, "modifications"),
			...getImportsByFolderStructure(`src/global/modifications`, (modification) => `import "../../global/modifications/${modification}";`),
			...getImportsByFolderStructure(`src/global/events`, (event) => `import "../../global/events/${event}";`),
			...getImportsByFolderStructure(`src/global/listeners`, (listener) => `import "../../global/listeners/${listener}";`),
			...getImportsByFolderStructure(`src/apps/${app}/modifications`, (modification) => `import "./modifications/${modification}";`),
			...getImportsByFolderStructure(`src/apps/${app}/events`, (event) => `import "./events/${event}";`),
			`import "../../global/after_app";`,
		];
		fs.writeFileSync(`src/apps/${app}/index.ts`, appIndexFileArray.join("\n"));
	}
}

function getImportsForSharedConfig(sharedFolderNames, element) {
	const imports = [];
	for (const sharedFolderName of sharedFolderNames) {
		imports.push(
			...getImportsByFolderStructure(
				`src/shared/${sharedFolderName}/${element}`,
				(item) => `import "../../shared/${sharedFolderName}/${element}/${item}";`
			)
		);
	}
	return imports;
}

function getImportsByFolderStructure(folderPath, generateImportStringFunction) {
	const files = fs.readdirSync(folderPath);
	const imports = [];
	for (const file of files) {
		imports.push(generateImportStringFunction(file));
	}
	return imports;
}
